### ISSUE TITLE
Fix: HTML Partial Loading

### ISSUE THREAD

**Issue by edm00se** [edm00se/parcel-v2-demo#2]
This works in local dev preview, but the dist/prod build doesn't work, outputting `undefined`. This likely has to do with the html loader implementation from parcel v2. The below screen shot and code surrounding it can be found in the [partial-html-loading branch](https://github.com/edm00se/parcel-v2-demo/tree/partial-html-loading).

![image](https://user-images.githubusercontent.com/622118/66761547-db50e780-ee69-11e9-9897-c2940942c123.png)

**Comment by edm00se** [comment]
Per commit f4533bc, this works locally, but fails in the build/dist copy of things. To view this, check out [branch `partial-html-loading`](https://github.com/edm00se/parcel-v2-demo/commits/partial-html-loading) and run locally without any parcel cache.

**Comment by edm00se** [comment]
<details><summary>

On latest nightly (`2.0.0-nightly.349`) this fails during `parcel serve src/index.html` and `parcel build src/index.html`.
</summary><p>

```
❯ npm run dev

> parcel-v2-demo@1.0.0 dev /Users/EMcCormick/Projects/eric/parcel-v2-demo
> parcel serve src/index.html

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/packager-html: HTML bundles must only contain one asset
AssertionError [ERR_ASSERTION]: HTML bundles must only contain one asset
    at Object.package (/Users/EMcCormick/Projects/eric/parcel-v2-demo/node_modules/@parcel/packager-html/lib/HTMLPackager.js:37:21)
    at PackagerRunner.package (/Users/EMcCormick/Projects/eric/parcel-v2-demo/node_modules/@parcel/core/lib/PackagerRunner.js:213:36)
    at async PackagerRunner.getBundleResult (/Users/EMcCormick/Projects/eric/parcel-v2-demo/node_modules/@parcel/core/lib/PackagerRunner.js:179:20)
    at async PackagerRunner.getBundleInfo (/Users/EMcCormick/Projects/eric/parcel-v2-demo/node_modules/@parcel/core/lib/PackagerRunner.js:171:9)
    at async Child.handleRequest (/Users/EMcCormick/Projects/eric/parcel-v2-demo/node_modules/@parcel/workers/lib/child.js:171:9)
```
</p></details>
